BUGFIX: Use `junction` type when symlinking directories on Windows.
It fixes an issue where `require` and `require.resolve` of a symlinked dependency would fail with an error such as:

```
Error: EPERM: operation not permitted, stat 'C:\workspace\packages\a-workspace-package\node_modules\antd'
    at Object.realpathSync (fs.js:1704:17)
    at toRealPath (internal/modules/cjs/loader.js:175:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:224:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:546:25)
    at Function.resolve (internal/modules/cjs/helpers.js:18:19)
```

I also removed the uneeded `{force: true}` option in `createSymlinkForDependency` since there is an `if` above checking that the symlink path doesn't exist yet.